// This file is auto-generated by @hey-api/openapi-ts

export const LinkCreateSchema = {
  type: "object",
  properties: {
    href: {
      type: "string",
      format: "uri",
    },
    label: {
      type: "string",
    },
    newTab: {
      type: "boolean",
      nullable: true,
    },
  },
  required: ["href", "label"],
  example: {
    href: "https://example.com",
    label: "Example",
    newTab: false,
  },
} as const;

export const LinkUpdateSchema = {
  type: "object",
  properties: {
    href: {
      type: "string",
      format: "uri",
    },
    label: {
      type: "string",
    },
    newTab: {
      type: "boolean",
      nullable: true,
      default: false,
    },
  },
  required: ["href", "label"],
  example: {
    href: "https://example.com",
    label: "Example",
    newTab: false,
  },
} as const;
