// This file is auto-generated by @hey-api/openapi-ts

export const LinkSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    href: {
      type: "string",
    },
    label: {
      type: "string",
    },
    newTab: {
      type: "boolean",
      nullable: true,
    },
    createdAt: {
      type: "string",
      nullable: true,
    },
    pageId: {
      type: "string",
    },
  },
  required: ["id", "href", "label", "newTab", "createdAt", "pageId"],
} as const;

export const LinkCreateSchema = {
  type: "object",
  properties: {
    href: {
      type: "string",
      format: "uri",
    },
    label: {
      type: "string",
    },
    newTab: {
      type: "boolean",
      nullable: true,
    },
  },
  required: ["href", "label"],
  example: {
    href: "https://example.com",
    label: "Example",
    newTab: false,
  },
} as const;

export const LinkUpdateSchema = {
  type: "object",
  properties: {
    href: {
      type: "string",
      format: "uri",
    },
    label: {
      type: "string",
    },
    newTab: {
      type: "boolean",
      nullable: true,
      default: false,
    },
  },
  required: ["href", "label"],
  example: {
    href: "https://example.com",
    label: "Example",
    newTab: false,
  },
} as const;

export const PageUpdateSchema = {
  type: "object",
  properties: {
    title: {
      type: "string",
    },
  },
  required: ["title"],
  example: {
    title: "https://example.com",
  },
} as const;
