// This file is auto-generated by @hey-api/openapi-ts

import type { GetPageResponse, ListPagesResponse } from "./types.gen.ts";

const pageSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  data.publishedAt = new Date(data.publishedAt);
  return data;
};

export const listPagesResponseTransformer = async (
  data: any,
): Promise<ListPagesResponse> => {
  data = data.map((item) => {
    return pageSchemaResponseTransformer(item);
  });
  return data;
};

export const getPageResponseTransformer = async (
  data: any,
): Promise<GetPageResponse> => {
  data = pageSchemaResponseTransformer(data);
  return data;
};
