// This file is auto-generated by @hey-api/openapi-ts

export type Link = {
  id: string;
  href: string;
  label: string;
  newTab: boolean;
  createdAt: string;
  pageId: string;
};

export type LinkCreate = {
  href: string;
  label: string;
  newTab?: boolean;
};

export type LinkUpdate = {
  href: string;
  label: string;
  newTab?: boolean;
};

export type PageUpdate = {
  title: string;
};

export type ListLinksData = {
  body?: never;
  path: {
    page_id: string;
  };
  query?: never;
};

export type ListLinksResponse = Array<Link>;

export type CreateLinkData = {
  body?: LinkCreate;
  path: {
    page_id: string;
  };
  query?: never;
};

export type CreateLinkResponse = string;

export type DeleteLinkData = {
  body?: never;
  path: {
    page_id: string;
    id: string;
  };
  query?: never;
};

export type DeleteLinkResponse = void;

export type UpdateLinkData = {
  body?: LinkUpdate;
  path: {
    page_id: string;
    id: string;
  };
  query?: never;
};

export type UpdateLinkResponse = "ok";

export type DeletePageData = {
  body?: never;
  path: {
    page_id: string;
  };
  query?: never;
};

export type DeletePageResponse = void;

export type UpdatePageData = {
  body?: PageUpdate;
  path: {
    page_id: string;
  };
  query?: never;
};

export type UpdatePageResponse = "ok";

export type GenerateHtmlData = {
  body?: {
    page_id: string;
  };
};

export type GetBySlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
};
